What is engineering? As I used to thought this question many years ago.
First of all, engineering should serve for human's needs, engineering work should be practical and useful.
Let's track down history, there're many great engineering works, from the Great Wall in the need of the Apollo Moonlanding Project, each was in the need of human, for his secure need, for his desire to explore outside world, and each required great human efforts. 
In today's world, human's need is reflected by the market, at the time engineering work can solve the production issue, there should 
be business work to find the market and drive the market, thus can make engineering benefit human more and let engineering people do the right work. From my logic, I strongly approve with the idea that "leaders in the engineering profession require a strong foundation in business, and that leaders in business benefit from a strong foundation in engineering. "  Holding this belief, I practiced 
myself in business world and sharped my business mind when doing several projects.  In Auguest 2011, I found that there is an irresistible trend to release the students and teachers from the heavy burden of taking and managing traditional paper based examinations. What if I could solve the problem? As I thought, I sponsored a system-level project which required a proficient knowledge in many different technology areas with a partner. We launched th system after four months' development and test. We also got our first buyer, Yangzhou University, and we received about nearly 10 thousand RMB. That's quite a lot for two sophomores!
Today, I'm glad to see that the system is benefiting thousands of students and teachers of Yangzhou University. What's more inspiring is that several other universities have contacted me and showed interests in that system. The story is not over. Engineering is not about just construction. The world will not be today's world, if it is. The true essence of engineering, I think, is the ideas and thoughts to lower the cost in construction and in repairment. Why didn't I sell my engineering work to the later universities who contacted me? Since I already know the maintenance cost behind the work, and also, I should spare time to finish
my studies. How can I low the cost of developing and maintenance? As I thought, I sponsored the project once again 
with five partners. First, I pursuaed my team to programming the work in LAMP(Linux+Apache+Mysql+PHP/Python) 
environment instead of windows' ones. Since the main cost of software engineering is maintenance, I decided to totally
take the concepts of Object-Oriented-Design(OOD). I also decided to no use any famous web application 
framework, such as Zend or Yii. I decided to build our own framework and use our own since, in my opinion, this kind
of experience will benefit more to my team in the future. In addition to OOD, I will also take the use of two other 
technologies, Model-View-Controller and Test-Driven-Development. All the thoughts and techniques our team will 
try this time are all in the need of lowing down the average cost of the whole developing and maintaining process.
